#cloud-config
autoinstall:
  version: 1
  refresh-installer:
    update: true
  apt:
    geoip: true
    preserve_sources_list: false
    primary:
    - arches: [amd64, i386]
      uri: http://ch.archive.ubuntu.com/ubuntu
    - arches: [default]
      uri: http://ports.ubuntu.com/ubuntu-ports
  identity:
    hostname: ubuntu-server
    # echo ubuntu | mkpasswd -m sha512crypt --stdin
    password: $6$hg2y5aO5DRejj9yl$2lW4Jkvi989B5QyeWmB7Qb2ulxwEXQYBshcGDv9ChBrcWYfidQ5uX/n8qSI7pLm3Ho7HeMKEKmRBnotTBlgtq0
    realname: Ubuntu User
    username: ubuntu
  keyboard:
    layout: us
  locale: en_US.UTF-8
  network:
    version: 2
    ethernets:
      id0:
        match:
          name: ens*
        dhcp4: true
        dhcp-identifier: mac
        dhcp4-overrides:
          use-dns: false
        nameservers:
          addresses:
          - 192.168.1.1
  ssh:
    allow-pw: true
    authorized-keys:
    # PatschifigPro
    - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDXbLntDByf0dQ7gOceUe0cWMwldAwEPMazpDCLk2pSxgawUF0kScXGIxWDQ+uag0y4g6iEwESw9u108V2t9QYJxM59TT8NFlFKe/+nRFcm7Sz2KhNITpH7GXBu1iRhx5AvJwLsD5GsLHuPU/+x+LK4EuGZX0vAJeNhp/zCWjwYTauRE2I/NkNZ69GkuSHro5ZmuwyRUeIuHEq4c7vCDY3C/HHMg5XI0EntqzsBAqcBVDUVW11jkM9RJ+FRQGLMRJ6sizVNWfM1A5kXnof/aCJW1wlIJBshFXwek7J0tk4UXEBkBc1T8c+ejfHgJP39vY2ZhH7/bzRpXHoNaPYIH8vOdspzgOJ8Srjb0E+sYPszjuRymqmBILZ3TEhgF275CXtH1BXnXcDDsbVf4KqGJxCEYZJ34cL9bQ9mHde1cdvhMlBviNOUz5+IwmUbWVdVhTC8jrmoa8fl73I42p2u8tHXXM4EfA4yWB2AkuCmRgkul/y0WJscXGpZTBaqBS0wBgE= dstaiger@MacBook-Pro.localdomain"
    # Spectracular
    - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDIwCSQRoXzu6Lha5DeadBiHswEwepgtqRclvuftv56kG4GJFId5jRmkvvrEzLIN9B4FwslG7rbVTjYoD3vdcjGJ3LpVCffskFIf2ebknPO/Rvm/VcdxXGFzxhh74VwY4vPThsEYZzc2z4A1y7RXkaI5um7i3qStq9Y7iSlblZJDSphsETc2g4wxvLtEnEBgf4R0eDfw2cPdVkXiqrihpOSaV7/4tK6FreGNUFB3shFDwPjR0ayspMvUzM+nXiyXr0qB5ex1MnH9HDkTBXlRa0UdRvNcCJXuGQ1W0AknD/nscpICNXEDSh/29Ppxxcg6C77MiD5SSLWScgCZhnHlC6sxftZTYRBGH+VpGdPU6B9faFIwaddhjSFtHqyIt1tDVIkF9sVugrq2rXGtyZY+wLS3m4P6RCWEvUMf7HQXzNl9cvPNqyHkKlEtl5b3yAdpnJyz+tmt4PfhBK8HusUW3I0viCAjTLlQ8kRcNwn0YzePFsrQgybzjBMRYKCEOw4K6k= dstaiger@MacBook-Pro.localdomain"
    install-server: true
  late-commands:
  - shutdown -h now
  # https://curtin.readthedocs.io/en/latest/topics/storage.html
  storage:
    swap:
      size: 0
    config:
    # Root Disk
    - id: root-disk-0
      type: disk
      path: /dev/sda
      wipe: superblock-recursive
      preserve: false
      grub_device: false
      name: ''
      ptable: gpt
    - id: root-partition-0
      type: partition
      device: root-disk-0
      size: 512M
      wipe: superblock
      flag: boot
      number: 1
      preserve: false
      grub_device: true
    - id: root-format-0
      type: format
      fstype: fat32
      volume: root-partition-0
      preserve: false
    - id: root-partition-1
      type: partition
      device: root-disk-0
      size: -1
      wipe: superblock
      flag: ''
      number: 2
      preserve: false
    - id: root-format-1
      type: format
      fstype: ext4
      volume: root-partition-1
      preserve: false
    - id: root-mount-0
      type: mount
      device: root-format-0
      path: /boot/efi
    - id: root-mount-1
      type: mount
      device: root-format-1
      path: /
    # # Block device for distributed storage
    # - id: block-disk-0
    #   type: disk
    #   path: /dev/nvme0n1
    #   wipe: superblock-recursive
    #   preserve: false
    #   grub_device: false
    #   name: ''
    #   ptable: gpt
