---

# Timezone for the servers
timezone: "Europe/Zurich"

# Set custom ntp servers
ntp_servers:
  primary:
  - "ntp12.metas.ch"
  - "time.cloudflare.com"
  fallback:
  - "0.ch.pool.ntp.org"
  - "1.ch.pool.ntp.org"
  - "2.ch.pool.ntp.org"
  - "3.ch.pool.ntp.org"

# Additional ssh public keys to add to the nodes
ssh_authorized_keys:
  # # PatschifigPro
  # - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDXbLntDByf0dQ7gOceUe0cWMwldAwEPMazpDCLk2pSxgawUF0kScXGIxWDQ+uag0y4g6iEwESw9u108V2t9QYJxM59TT8NFlFKe/+nRFcm7Sz2KhNITpH7GXBu1iRhx5AvJwLsD5GsLHuPU/+x+LK4EuGZX0vAJeNhp/zCWjwYTauRE2I/NkNZ69GkuSHro5ZmuwyRUeIuHEq4c7vCDY3C/HHMg5XI0EntqzsBAqcBVDUVW11jkM9RJ+FRQGLMRJ6sizVNWfM1A5kXnof/aCJW1wlIJBshFXwek7J0tk4UXEBkBc1T8c+ejfHgJP39vY2ZhH7/bzRpXHoNaPYIH8vOdspzgOJ8Srjb0E+sYPszjuRymqmBILZ3TEhgF275CXtH1BXnXcDDsbVf4KqGJxCEYZJ34cL9bQ9mHde1cdvhMlBviNOUz5+IwmUbWVdVhTC8jrmoa8fl73I42p2u8tHXXM4EfA4yWB2AkuCmRgkul/y0WJscXGpZTBaqBS0wBgE= dstaiger@MacBook-Pro.localdomain"
  # # Spectracular
  # - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDIwCSQRoXzu6Lha5DeadBiHswEwepgtqRclvuftv56kG4GJFId5jRmkvvrEzLIN9B4FwslG7rbVTjYoD3vdcjGJ3LpVCffskFIf2ebknPO/Rvm/VcdxXGFzxhh74VwY4vPThsEYZzc2z4A1y7RXkaI5um7i3qStq9Y7iSlblZJDSphsETc2g4wxvLtEnEBgf4R0eDfw2cPdVkXiqrihpOSaV7/4tK6FreGNUFB3shFDwPjR0ayspMvUzM+nXiyXr0qB5ex1MnH9HDkTBXlRa0UdRvNcCJXuGQ1W0AknD/nscpICNXEDSh/29Ppxxcg6C77MiD5SSLWScgCZhnHlC6sxftZTYRBGH+VpGdPU6B9faFIwaddhjSFtHqyIt1tDVIkF9sVugrq2rXGtyZY+wLS3m4P6RCWEvUMf7HQXzNl9cvPNqyHkKlEtl5b3yAdpnJyz+tmt4PfhBK8HusUW3I0viCAjTLlQ8kRcNwn0YzePFsrQgybzjBMRYKCEOw4K6k= dstaiger@MacBook-Pro.localdomain"
