---

all:
  children:
    # Control Plane group, do not change the 'control-plane' name
    # hosts should match the filenames in 'host_vars'
    control-nodes:
      hosts:
        nuc-2:
    # Node group, do not change the 'node' name
    # hosts should match the filenames in 'host_vars'
    generic-nodes:
      hosts:
        nuc-3:
        # k8s-generic-node-b:
        # k8s-generic-node-c:
        # k8s-generic-node-d:
        # k8s-generic-node-e:
    # Storage group, these are my NAS devices
    # hosts should match the filenames in 'host_vars'
    storage:
      hosts:
        # nas-rocinante:
        # nas-serenity:
